from fpdf import FPDF
from datetime import datetime
import os

class ContractBot:
    def __init__(self):
        print("[Legal] Contract Agent Ready.")

    def generate_sales_agreement(self, buyer_name, seller_name, item, amount, price):
        """
        Generates a formal PDF invoice/contract.
        """
        pdf = FPDF()
        pdf.add_page()
        
        # 1. Header
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(200, 10, txt="GRAM-OS: RURAL SALES AGREEMENT", ln=1, align='C')
        pdf.ln(10) # Line break

        # 2. Details
        pdf.set_font("Arial", size=12)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        content = [
            f"Date: {timestamp}",
            f"Seller: {seller_name}",
            f"Buyer: {buyer_name}",
            "--------------------------------------------------",
            f"Item Sold: {item}",
            f"Quantity: {amount}",
            f"Total Price: INR {price}",
            "--------------------------------------------------",
            "Terms: Payment to be made within 7 days.",
            "This document is digitally generated by Gram-OS offline."
        ]

        for line in content:
            pdf.cell(200, 10, txt=line, ln=1, align='L')

        # 3. Save File
        filename = f"Contract_{buyer_name}_{datetime.now().strftime('%Y%m%d')}.pdf"
        pdf.output(filename)
        
        print(f"[Legal] Contract generated: {filename}")
        return filename

# --- Test Block ---
if __name__ == "__main__":
    agent = ContractBot()
    # Mocking a voice input conversion
    agent.generate_sales_agreement(
        buyer_name="Raju",
        seller_name="Amit (User)",
        item="Wheat Seeds (High Yield)",
        amount="50 kg",
        price="2500"
    )